name: image-ci

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  generate-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all tags for accurate tagging

      - name: Generate Image Tag
        id: generate-image-tag
        run: |
          # Generate a unique image tag based on the latest git tag or commit
          TAG=$(git describe --tags --abbrev=0 || echo "0.1.0")
          SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="$TAG-$SHA"
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG"
